Harmonise color on front-end
Nanocloud/nanocloud pull request #201
Opened 2016-09-07 13:42 UTC by corentindrouet

It add the spectrum-color-picker component,
class to css, and template
and a live previous of the color selected.

Add a function on Properties controller to calculated a lighten and darken color when the color is choose,
and the page is refreshed.

2016-09-08 04:22 UTC, dynamiccast commented
Few spots are still no customizable:
- Help tooltip, copy tooltip on user profil
- Edit icon on profile
- Group checkbox to add members/applications
- Stay clicked on a button while leaving hover area
- Input border on focus
- Team create button
- Alert box background (machine page where there is no machines)

2016-09-08 04:22 UTC, dynamiccast commented
I would be nice to auto refresh the page once "choose" is clicked.

2016-09-13 08:02 UTC, dynamiccast commented
Configuration fields need to be bordered in green.

2016-09-13 10:07 UTC, dynamiccast commented
One more mistake. Try to stay clicked on the upper right logout button. It's border remains blue.

2016-09-15 15:29 UTC, spacewoox commented on assets/app/styles/global.scss
> +    background-color: #eef4f9;
-> background-color: $gray-lighter;

2016-09-15 15:41 UTC, spacewoox commented on assets/app/styles/global.scss
> +.btn-color-default {
&:hover,
&:focus,
&:active {
  background-color: $blue-darken;
}

2016-09-15 15:42 UTC, spacewoox commented on assets/app/styles/global.scss
> +    &:hover {
useless

2016-09-15 15:43 UTC, spacewoox commented on assets/app/styles/global.scss
> +  border-color: $blue-lighten;
should be on top

2016-09-15 15:43 UTC, spacewoox commented on assets/app/styles/global.scss
> +.icon-coloir-default {
coloir

2016-09-15 15:47 UTC, spacewoox commented on assets/app/reset-password/token/template.hbs
> +          </form>
wrong indent

2016-09-15 15:48 UTC, spacewoox requested changes

2016-10-05 09:25 UTC, merged