Add live modification of the pool size
Nanocloud/nanocloud pull request #315
Opened 2016-10-03 12:55 UTC by Leblantoine

Fixes #296 
You can change the machine pool size from the config tab.
When `machinePoolSize` is changed, now the number of machine in the pool is automatically updated.
If there is not enough machines, some starts.
In the opposite case, if the number of running machine is superior of the pool size, no machine will be destroyed.

Add unit test for `updateMachinesPool`.

2016-10-03 14:20 UTC, dynamiccast requested changes

2016-10-03 14:20 UTC, dynamiccast commented on tests/unit/services/MachineService.test.js
> +    before('Set machinePoolSize at 0', function(done) {
at -> to

2016-10-03 14:20 UTC, dynamiccast commented on tests/unit/services/MachineService.test.js
> +          return MachineService.updateMachinesPool();
Is this not supposed to be performed automatically ?

2016-10-03 14:20 UTC, dynamiccast commented on tests/unit/services/MachineService.test.js
> +    it('Should not destroy running machine when machinePoolSize shrink', (done) => {
shrink -> shrinks

2016-10-03 14:20 UTC, dynamiccast commented on tests/unit/services/MachineService.test.js
> +            throw new Error('Should still have 4 running machines');
Why ? The pool should skring down to 2 machines.

2016-10-04 09:50 UTC, Leblantoine commented on tests/unit/services/MachineService.test.js
> +          return MachineService.updateMachinesPool();
This performed automatically in `ConfigController` not in `ConfigService`. If we check this in `ConfigService` driver is not initialized for the first set and generate an error.

2016-10-04 10:02 UTC, dynamiccast commented on tests/unit/services/MachineService.test.js
> +          return MachineService.updateMachinesPool();
Legit

2016-10-04 12:35 UTC, dynamiccast approved these changes

2016-10-04 16:20 UTC, merged