Add clipboard integration for Photon.
Nanocloud/nanocloud pull request #478
Opened 2016-11-14 09:57 UTC by romain-ortega

This PR fixes #446.
Clipboard is sent from VM to the browser in a textarea when clicking on 'Clipboard' action on the VDI tab.
Clipboard is set automatically when the content of this textarea changes.

2016-11-16 15:28 UTC, dynamiccast requested changes

2016-11-16 15:28 UTC, dynamiccast commented on photon/conductor.cc
> +	this->channel = nullptr;
Wrong indentation

2016-11-16 15:28 UTC, dynamiccast commented on photon/input_manager.h
> +#endif  // PHOTON_INPUT_MANAG ER_H_
Why did you change that ?

2016-11-18 17:24 UTC, Gentux approved these changes

2016-11-22 18:47 UTC, dynamiccast approved these changes

2016-11-23 14:59 UTC, merged